# Comprehensive Exams {#comps}

We will be experimenting with a prospective exam model which is heavily built around questions which target their preparation for dissertation work. This means questions targeted at how well they have integrated areas related to their dissertation, prepared methods/analytic approaches to target their question, critically evaluated key areas and known limitations, and show understanding of how their topic will push forward scholarly work.Note this exam is an exit point exam meaning it should be a real possibility for some students to fail and depart with their MA degree. Rogelberg indicated this happened at UNC meaning it still is intended to be a rigorous process. For comps we need a procedure, set of criteria, timeline, and decision on how many phases to complete. I have found many prospective comp policies from other doctoral programs which are very thorough and provide good examples, such as:


+ [McGill](https://www.mcgill.ca/socialwork/prospective/phd/comprehensive-exam)
+ [UMass](https://www.umass.edu/communication/node/861)
+ [PennState](http://gradschool.psu.edu/graduate-education-policies/gcac/gcac-600/gcac-604-qualifying-exam/)

An example of a traditional I/O comp exams are as follows:

+ [Texas A&M](https://liberalarts.tamu.edu/wp-content/uploads/sites/2/2018/02/I-O-area-comps-policy-Nov-16th-2015.pdf)

