# Student I/O Group, Mentorship, and Program Culture {#culture}

Maybe shift to "how to navigate the program" - initial PhD advisor (upon matriculation) versus selecting one in pursuit of the PhD

Policies and procedures for an official I/O student group (perhaps Eagle I/O is sufficient) with officers and roles charged with social events, mentoring, speakers, assembling student resources, putting together SIOP reception, etc… Basically a charter and set of annual tasks for a select set of I/O Doctoral and MA student officers to complete to improve the strength of the bonds between the students and extracurricular opportunities to strengthen their vocational self-concepts. Further, we need to make sure one faculty member (John for now) is always overseeing the mentorship and eagle I/O group to ensure its continuity. Here are several examples of such groups and their offerings at other I/O programs

Characteristics we value (self-initiative, internal locus-of-control), engagement with alumni and bringing external speakers on campus, encouragement of METRO & SIOP, but we’re not going to delineate a process to build and maintain culture

+ [Columbia’s OHDCC group](http://ohdcc.org/)
+ [George Mason I/O Student Group](https://io.gmu.edu/iopsa)
+ [CSUSB’s Student IO Group](https://artsandsciences.utulsa.edu/wp-content/uploads/sites/6/2015/02/GRASP-Handbook-2015-2016.pdf)
+ [Student Advice Guide from GRASP at Tulsa](https://artsandsciences.utulsa.edu/wp-content/uploads/sites/6/2015/02/GRASP-Handbook-2015-2016.pdf)
+ [Colorado’s I/O Group](http://iopac.colostate.edu/)

We already have an official mentorship guide and procedure. However, the program is still growing organically through John’s work and may expand to include other student responsibilities. Given this, perhaps a high-level, one page overview of current procedures, expectations, and roles on the mentorship program for the handbook? Something like a general overview to guide PhD and MA students on scheduling, involvement, and primary tasks. 
